### ISSUE TITLE
Problem using Ocarina code generation with the ADIRU example

### ISSUE THREAD

**Issue by CaptainSeum** [OpenAADL/AADLib#18]
Hi,

I'm trying to use Ocarina on the ADIRU example but I get the following errors:

`Frontends : error : partitions.aadl:304:55: parsing Error_Condition, token ')' is expected, found token 'and'
Frontends : error : adiru_devices.aadl:26:61: parsing Error_Behavior_State, token ':' is expected, found token ';'
adiru_devices.aadl:6:08: EMV2 (identifier) is not a package or a property set visible or existing
Cannot analyze AADL specifications`

I would like to try this code on an RTOS, does somebody can help ?

(I use OSATE v2.5.2)

Thanks

**Comment by yoogx** [comment]
Use Ocarina from the command line, that will be easier. See AADLib doc for details

There is an issue with the EMV2 description that you do not need for code generation. Also, ADIRU has been tested on ARINC653  RTOS a while back

**Comment by CaptainSeum** [comment]
Thank you for your answer.

I should have been more accurate, test ADIRU generated code on ARINC653 RTOS that my company is developing. 

Where can I find the documentation for AADLib ?

**Comment by yoogx** [comment]
Patch for openaadl/osate2-ocarina#16 addresses this issue
I could generate code for VxWorks653 from the top menu. Note I canot test it.

**Comment by yoogx** [comment]
Regarding AADLib doc, Ocarina has it all:
either you compiled it as part of Ocarina, then simply go in the corresponding example directory and run "make help"
or you do it from scratch, install Ocarina, put it in your path, then ./support/reconfig to build configure, then ./configure && make install to install stuff, then go in example directory
