### ISSUE TITLE
Arinc653_annex example 1

### ISSUE THREAD

**Issue by CaptainSeum** [OpenAADL/AADLib#19]
Hi,

I'm trying to run the Arinc653_annex example 1 and I have two question:

- What should I use as make command to create generic code for ARINC653 compliant RTOS

- When I try to generate code for vxWorks653 OS, addind to the aadl file an specific implementation, I end up with the following logs:

`partitionedsystemexample.aadl:111:05: ARINC653::HM_Errors (property association) does not point to anything
partitionedsystemexample.aadl:112:05:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:112:19:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:112:38:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:112:53:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:113:05: ARINC653::HM_Process_Recovery_actions (property association) does not point to anything
partitionedsystemexample.aadl:114:05:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:114:21:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:114:38:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:114:46:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:133:05: ARINC653::HM_Errors (property association) does not point to anything
partitionedsystemexample.aadl:133:28:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:133:42:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:133:61:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:133:76:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:134:05: ARINC653::HM_Process_Recovery_Actions (property association) does not point to anything
partitionedsystemexample.aadl:134:46:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:134:62:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:134:79:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:134:96:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:156:05: ARINC653::HM_Errors (property association) does not point to anything
partitionedsystemexample.aadl:156:28:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:156:42:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:156:61:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:156:76:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:157:05: ARINC653::HM_Process_Recovery_Actions (property association) does not point to anything
partitionedsystemexample.aadl:157:46:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:157:62:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:157:76:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:157:90:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:174:05: ARINC653::HM_Errors (property association) does not point to anything
partitionedsystemexample.aadl:174:28:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:174:42:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:174:61:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:174:76:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:175:05: ARINC653::HM_Process_Recovery_Actions (property association) does not point to anything
partitionedsystemexample.aadl:175:46:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:175:62:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:175:79:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:175:96:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:254:05: ARINC653::Partition_Slots (property association) does not point to anything
partitionedsystemexample.aadl:255:05: ARINC653::Slots_Allocation (property association) does not point to anything
partitionedsystemexample.aadl:256:05: ARINC653::HM_Errors (property association) does not point to anything
partitionedsystemexample.aadl:256:28:  (property term) does not point to anything or to something unreachable
partitionedsystemexample.aadl:257:05: ARINC653::HM_Module_Recovery_Actions (property association) does not point to anything
partitionedsystemexample.aadl:257:45:  (property term) does not point to anything or to something unreachable
Cannot analyze AADL specifications
Makefile:512: recipe for target 'vxworks653_code' failed
make: *** [vxworks653_code] Error 1`

It seems it connot reach ARINC653 annex.

Thanks

**Comment by yoogx** [comment]
neraka% make help
Available targets:  parse-aadl real deos_conf vxworks653_conf deos_code vxworks653_code
neraka% make vxworks653_code 
ocarina -aadlv2 -v -y -disable-annexes=emv2 -I/Users/hugues/Desktop/Work/Dev/git/ocarina/resources/runtime/aadlib/src/property_set -I/Users/hugues/Desktop/Work/Dev/git/ocarina/resources/runtime/aadlib/src/aadl -I/Users/hugues/Desktop/Work/Dev/git/ocarina/resources/runtime/aadlib/examples/adiru  -g pok_c -k vxworks653 -r adiru.impl \
		/Users/hugues/Desktop/Work/Dev/git/ocarina/resources/runtime/aadlib/examples/adiru/model.aadl
Ocarina 2017.x (Working Copy from rc571d16)
Copyright (c) 2003-2009 Telecom ParisTech, 2010-2019 ESA & ISAE
Build date: 
Loading file /Users/hugues/Desktop/Work/Dev/git/ocarina/resources/runtime/aadlib/examples/adiru/model.aadl
Loading file partitions.aadl
Loading file adiru_devices.aadl
Loading file adiru_memory.aadl
Loading file adiru_processor.aadl
Loading file arinc653.aadl
Loading file threads.aadl
Loading file shm_datatype.aadl
Loading file adiru_errlibrary.aadl
Loading file emv2.aadl
Loading file subprograms.aadl
Loading file data_model.aadl
Loading of all files done
Model parsing: completed

partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:16:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:134:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:134:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:239:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:239:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:239:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:239:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
partitions.aadl:319:03 Backends: warning : Priority_Range property is not defined
Backends: warning : generated-code already exists
Code generation: completed

neraka%

**Comment by CaptainSeum** [comment]
I’m sorry I was not enough specific. The example I’m talking about is arinc653_annex not the Adiru, the adiru example code generation is working (at least for vxworks and DeOs)

**Comment by yoogx** [comment]
only ADIRU is proven to work for code generation. The example you are referring to comes from the ARINC653 annex and only illustrate corresponding modelling patterns.

**Comment by CaptainSeum** [comment]
Yes I know. What would it takes to create a model from scratch that would fit the needs of Ocarina ? Is there any AADL development guidelines to fit Ocarina tooling purposes ?

**Comment by yoogx** [comment]
Not publicly available. Use the existing examples as templates

**Comment by CaptainSeum** [comment]
Ok. Does code generation support the whole arinc653 annex (as semaphores, blackboards, ...) ?
