### ISSUE TITLE
How to bind physical model  with functional model

### ISSUE THREAD

**Issue by yanghaiyun123** [OpenAADL/AADLib#20]
Please give an example for binding physical model with functional model, thank you  very much!

**Comment by yoogx** [comment]
This is an issue tracker for bug related to AADLIb, not a forum on AADL. Check AADL mailing list for these questions.

**Comment by yanghaiyun123** [comment]
Thank you for your reply! I would like to know how I can find the  AADL mailing list.

**Comment by yoogx** [comment]
https://lists.sei.cmu.edu/mailman/listinfo/aadl-modeling
